#******************************************************************************
# Makefile<lib1>                                    XL - An extensible language
#******************************************************************************
#
#  File Description:
#
#
#
#
#
#
#
#
#
#
#******************************************************************************
# (C) 2017 Christophe de Dinechin <christophe@dinechin.org>
#  This software is licensed under the GNU General Public License v3
#  See LICENSE file for details.
#******************************************************************************

BUILD=../
SOURCES=lib1.c
PRODUCTS=lib1.dll

include $(BUILD)rules.mk
